/** @noSelf **/

declare class Character {
    static GetName(): string
    static GetClass(): string
    static GetFaction(): string
    static GetRace(): string
    static GetGender(): string
    static GetLevel(): number
    static GetChampionPoints(): number
    static GetAlliance(): string
    static GetAllianceId(): number
    static GetZone(): string
    static GetZoneId(): number
    static GetSubZone(): string
    static GetSubZoneId(): number
    static GetLocation(): string
    static GetLocationId(): number
    static GetAccountName(): string
    static GetDisplayName(): string
    static GetId(): number
    static GetGuildId(): number
    static GetGuildName(): string
    static GetGuildIndex(): number
    static GetGuildCount(): number
    static GetGuildRank(): number
    static GetGuildRankName(): string
    static GetGuildRankIcon(): string
    static GetGuildRankIconSmall(): string
    static GetGuildRankId(): number
    static GetGuildAlliance(): string
    static GetGuildAllianceId(): number
    static GetGuildAllianceIcon(): string
    static GetGuildAllianceIconSmall(): string
    static GetGuildAllianceColor(): string
    static GetGuildAllianceColorRGB(): number
    static GetGuildAllianceColorRGBA(): number
    static GetGuildAllianceColorHex(): string
    static GetGuildAllianceColorHexRGB(): string
    static GetGuildAllianceColorHexRGBA(): string
    static GetGuildAllianceColorRGBPercent(): number
    static GetGuildAllianceColorRGBAPercent(): number
}